# Data Analysis Using NumPy and Pandas.

In [109]:
!pip install Numpy
!pip install Pandas
import numpy as np
import pandas as pd

Requirement already satisfied: Numpy in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (2.5.2)
Requirement already satisfied: Pandas in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (from Pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (from Pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (from Pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ADMIN\.conda\envs\py313\Lib\site-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)

## Objectives
🟣  Create and manage datasets using Python dictionaries and Pandas DataFrames.<br>
🟣  Perform column selection, row filtering, and subset retrieval.<br>
🟣 Apply aggregation functions (groupby, mean, value_counts, unique) for data summarization.<br>
🟣 Manipulate data by updating values, adding new columns, and removing rows/columns.<br>
🟣 Explore NumPy and Pandas operations for efficient data analysis.<br>

&nbsp;

## Data analysis using NumPy

🔵 Numerical Python (NumPy) → A powerful Python library for numerical computing.<br>
🔵 Core feature: Arrays → Provides the ndarray object for fast, efficient storage and manipulation of large datasets.<br>
🔵 Performance → Much faster than Python lists.<br>
🔵 Mathematical functions → Supports linear algebra, statistics, Fourier transforms, and more.<br>
🔵 Indexing & slicing → Flexible ways to access and manipulate subsets of data.<br>
🔵 Integration → Works seamlessly with Pandas, Matplotlib, and SciPy for data analysis and visualization.<br>
🔵 Applications → Widely used in data science, machine learning, image processing, and scientific computing.

In [2]:
# 1. Create a 1D NumPy Array:
# Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:
# [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
temp_w1=[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
temp_w1=np.array(temp_w1)
temp_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [4]:
#2. Inspection and Properties:
# Inspect the shape, data type, and the number of elements in the array. 
# Inspect the shape of the temperatures_w1 array.

# shape
temp_w1.shape

(7,)

In [15]:
# data type
temp_w1.dtype

dtype('float64')

In [17]:
# the number of element
temp_w1.size

7

In [ ]:
#Output

In [5]:
print('\nInspection and Properties')
print()
print('Shape          :', temp_w1.shape)
print('Data type      :', temp_w1.dtype)
print('Num of element :', temp_w1.size)

Inspection and Properties

Shape          : (7,)
Data type      : float64
Num of element : 7

In [24]:
#Array Operations:
# ● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:

# conversion Formula 
# Fahrenheit = (Celsius * 9/5) + 32

<u>Explanation</u><br>
- Each Celsius value is multiplied by 9/5=1.8
- Then add 32 to shift into the Fahrenheit scale.

For example:
 22.5°C → (22.5 x 1.8)+32=72.5° F

In [6]:
temp_fa=(temp_w1 * 9/5)+32

print('Temperature in Fahrenheit :', temp_fa)

Temperature in Fahrenheit : [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [11]:
# ● Find the maximum, minimum, and mean temperatures for the week.
np.max(temp_fa)

np.float64(78.98)

In [12]:
np.min(temp_fa)

np.float64(69.44)

In [13]:
np.mean(temp_fa)

np.float64(74.37714285714286)

In [16]:
# Temperature numerical calculation

print('Max / Min / Mean ')
print()
print('Maximum :', np.max(temp_fa))
print('Minimum :', np.min(temp_fa))
print('Mean    :', np.mean(temp_fa))

Max / Min / Mean

Maximum : 78.98
Minimum : 69.44
Mean    : 74.37714285714286


## Array Slicing and Indexing</u><br>
- Explanation of Array Slicing and Indexing<br>
<u>Indexing </u> <br>
- Indexing is used to access individual elements of an array.<br>
 <u> Slicing  </u><br>
- Slicing allows you to extract a range of elements using [start:end].<br>

In [ ]:
# 4. Array Slicing and Indexing: --
# Extract the temperatures for the first three days of the week. -->
# Extract the temperatures for the weekend (last two days). -->
# Extract the temperatures for the middle three days of the week. -->
# reference=array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [17]:
#Extract the temperatures for the first three days of the week.
temp_fa[0:3]

array([72.5 , 77.54, 69.44])

In [19]:
#Extract the temperatures for the weekend (last two days). 
#reference=array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])
temp_fa[5:]

array([76.64, 71.42])

In [ ]:
#Extract the temperatures for the middle three days of the week

In [26]:

# First three days (index 0,1,2)
# Weekend (last two days → index 5,6)
# Middle three days (index 2,3,4)
print('Slicing and Indexing(Temperatures)')
print('\nTemp for the first three days   :', temp_fa[0:3])
print('Temp for the last two days      :', temp_fa[-2:])
print('Temp for the middle three days  :', temp_fa[2:5])

Slicing and Indexing(Temperatures)

Temp for the first three days   : [72.5  77.54 69.44]
Temp for the last two days      : [76.64 71.42]
Temp for the middle three days  : [69.44 74.12 78.98]

In [ ]:
#5. Create a 2D Array:
# Create a 2D NumPy array named temperatures where each row represents
# temperatures for a different week:
# ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
# ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [28]:
temp2d=[
            [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
             [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
]

arr_2d=np.array(temp2d)
arr_2d

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
# 6. Inspect and Slice the 2D Array:
# ● Inspect and print the shape, data type, and total number of elements in the temperatures array.
# ● Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [33]:
# ● Inspect and print the shape, data type, and total number of elements in the temperatures array
print('Inspect and Slice')
print('\nTemp Shape             :', arr_2d.shape)
print('Temp Data type         :', arr_2d.dtype)
print('Temp (Num of elements) :', arr_2d.size)

Inspect and Slice

Temp Shape             : (2, 7)
Temp Data type         : float64
Temp (Num of elements) : 14

In [34]:
# Extract the temperatures for each week and the weekends (last two days) for both weeks.
arr_2d

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [47]:
week_1=arr_2d[0]
week_2=arr_2d[1]

print('======Temp for each week======')
print('week_1 :', week_1)
print('week_2 :', week_2)
print('\n======Temp for weekend(Last two days) for both weeks======')
print('weekend_1 :', week_1[-2:])
print('weekend_2 :', week_2[-2:])

======Temp for each week======
week_1 : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
week_2 : [19.2 22.5 21.3 24.  23.5 22.8 20.1]

======Temp for weekend(Last two days) for both weeks======
weekend_1 : [24.8 21.9]
weekend_2 : [22.8 20.1]

# Pandas Series

- A Pandas Series is a one‑dimensional labeled array that can hold data of any type 
- (integers, floats, strings, objects).
       
<u> Structure  </u>
- It consists of two main parts:

- Values → The actual data.
- Index  → Labels that identify each element.

🟡 Accessing Data

- By index label → marks['Rank2'] → 92
- By position → marks[1] → 92

🟠 Key Features

- Handles missing data gracefully (NaN).
- Supports vectorized operations (fast calculations).
- Can be created from lists, dictionaries, or NumPy arrays.

  ✨ In short: A Pandas Series is like a column in Excel or a 1D NumPy array with labels, making it powerful for data analysis.

In [ ]:
# 1. Creating Pandas Series:
# ● Create a Pandas Series named marks with the following data:
# ➢ Marks: 95, 92, 89, 85, 80
# ➢ Custom Index: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [50]:
#Creating Pandas Series:
marks=pd.Series( [95,92,89,85,80],
index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print('pandas series')
print()
print(marks)

pandas series

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
# 2. Indexing and Slicing:
# ● Use the integer index position to access the mark of the 1st rank student.
# ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
# ● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [62]:
# ● Use the integer index position to access the mark of the 1st rank student.
print(marks.iloc[0])

95

In [58]:
# ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
print(marks.loc[['Rank1','Rank2','Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [59]:
# ● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
print(marks.iloc[2])

89

In [60]:
# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.
print(marks[marks> 90])

Rank1    95
Rank2    92
dtype: int64

In [ ]:
# 3. Manipulating Series:
# ● Modify the mark of the student with the 1st rank to 100.
# ● Remove the entry corresponding to the last rank from the Series.
# ● Compute the CGPA by dividing each mark in the Series by 10.

In [64]:
# ● Modify the mark of the student with the 1st rank to 100.
marks['Rank1']=100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [73]:
# ● Remove the entry corresponding to the last rank from the Series.
marks = marks.drop('Rank5')
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [92]:
# ● Compute the CGPA by dividing each mark in the Series by 10.
CGPA=marks/10
print('Marks:\n'+str(marks))
print()
print('CGPA:\n'+str(CGPA))

Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [98]:
# using dataframe CGPA
df = pd.DataFrame({
    'Marks': marks,
    'CGPA': CGPA
})
df

       Marks  CGPA
Rank1    100  10.0
Rank2     92   9.2
Rank3     89   8.9
Rank4     85   8.5

# Pandas DataFrame
## # 1. Creating Pandas DataFrame:

In [ ]:
# 1. Creating Pandas DataFrame:

# ● Create a Pandas DataFrame named transactions with the following data: ➢
# TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
# ➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',

# 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
# ➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
# 'North'
# ➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

🔵 Definition  
- A Pandas DataFrame is a two‑dimensional labeled data structure with rows and columns, similar to an Excel spreadsheet or SQL table.

🟢 Structure

- Rows → Represent individual records/observations.
- Columns → Represent variables/attributes.
- Each column is essentially a Pandas Series.

🟡 Key Features

- Handles heterogeneous data (different types in different columns).
- Supports indexing and slicing for rows and columns.

In [112]:
data={
    "TransactionID" : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    "Region"         : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'],
    "Amount"        :[ 200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
    
}
df_data=pd.DataFrame(data)
df_data

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

## 2. Data Exploration

<u> Purpose</u>
- Identify the types of variables (numeric, categorical, text).
- Detect missing values, duplicates, or inconsistencies.
- Summarize distributions and key statistics.
- Gain insights before applying complex models or transformations.
<u>🟡 Benefits</u>

- Provides a clear understanding of dataset quality.
- Helps in deciding preprocessing steps (cleaning, transformation).
- Reveals trends and anomalies early.
- Guides feature selection for machine learning.

<u>🟣 Common Techniques</u>

- Viewing data → df.head(), df.tail(), df.info(), df.describe()
- Unique values → df['Column'].unique()
- Value counts → df['Column'].value_counts()
- Grouping & aggregation → df.groupby('Column').mean()

In [ ]:
# ● Display the transactions DataFrame and its basic information, including head, tail,
# shape, column names, and data types.
# ● Display only the 'ProductCategory' and 'Amount' columns.
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
# ● Find the value counts for the 'ProductCategory' column.
# ● Find the unique values in the 'Region' column.
# ● Group by 'Region' and find the mean amount for each region.

In [114]:
# ● Display the transactions DataFrame and its basic information, including head, tail,
# shape, column names, and data types.
df_data.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [115]:
#tail()
df_data.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [116]:
#shape
df_data.shape

(10, 4)

In [117]:
#column name
df_data.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [122]:
#data type
df_data.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [124]:
## ● Display only the 'ProductCategory' and 'Amount' columns.
df_data[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [127]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
# Last 3 columns
df_data.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [130]:
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
filter_df= df_data[(df_data['Region'] == 'North') & (df_data['Amount'] > 200)]
print(filter_df)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [131]:
# ● Find the value counts for the 'ProductCategory' column.
df_data['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [132]:
# ● Find the unique values in the 'Region' column.
df_data['Region'].unique()

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [134]:
# ● Group by 'Region' and find the mean amount for each region.
mean_amount = df_data.groupby('Region')['Amount'].mean()
print(mean_amount)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

## 3. Manipulating the DataFrame:

In [ ]:
# 3. Manipulating the DataFrame:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.
# ● Remove the row with TransactionID 109.
# ● Delete the 'Discount' column from the DataFrame.

In [136]:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
import pandas as pd

# 1. Modify 'Amount' for TransactionID 102 to 165
df_data.loc[df_data['TransactionID'] == 102, 'Amount'] = 165


print(df_data)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [138]:
# 2. Add a new column 'Discount' (10% of Amount)
df_data['Discount'] = df_data['Amount'] * 0.10
print(df_data)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [140]:
# 3. Remove the row with TransactionID 109
df_data = df_data[df_data['TransactionID'] != 109]
print(df_data)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [141]:
# 4. Delete the 'Discount' column
df_data = df_data.drop(columns=['Discount'])
print(df_data)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

================================= Thank You=======================================